import "./globals.css";
import { Inter } from "next/font/google";
import { Sidebar, SidebarContent, SidebarProvider } from "@/components/ui/sidebar";
import { FinanceSidebar } from "@/components/sidebar";
import { FinanceHeader } from "@/components/header";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider className="relative">
          <ThemeProvider attribute="class" defaultTheme="light">
            <div className="flex h-screen overflow-hidden w-full min-w-screen">
              <Sidebar className="border-r relative">
                <SidebarContent className="relative">
                  <FinanceSidebar  />
                </SidebarContent>
              </Sidebar>
              <div className="flex flex-1 flex-col overflow-hidden w-full">
                <FinanceHeader />
                <main className="flex-1 overflow-y-auto p-8 w-full">
                  {children}
                </main>
              </div>
            </div>
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
