import {
  Sidebar,
  SidebarContent,
  SidebarProvider,
} from "@/components/ui/sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import { InventorySidebar } from "@/components/inventory-sidebar";
import { InventoryHeader } from "@/components/inventory-header";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <div className="flex h-screen overflow-hidden w-full">
              <Sidebar collapsible="icon" className="border-r">
                <SidebarContent>
                  <InventorySidebar />
                </SidebarContent>
              </Sidebar>
              <div className="flex flex-col flex-1 overflow-hidden">
                <InventoryHeader />
                <main className="flex-1 overflow-y-auto p-6 w-full">
                  {children}
                </main>
              </div>
            </div>
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
